name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17"
          otp-version: "27"

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix deps.clean --unused

      - name: Check compilation warnings
        run: mix compile --warnings-as-errors

      - name: Run Format checker
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo

      - name: Run Tests
        run: mix test

      - name: Run Dyalyzer
        run: mix dialyzer
